- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    home: /app
    shell: /sbin/nologin/
    system: true

- name: "download {{ component }} code from git"
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: /tmp/{{ component }}-v3.zip

- name: "extract {{ component }} code"
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}-v3.zip"
    dest: /app
    remote_src: yes
  

