- name: Task level variables
  hosts: frontend
  vars:
    NAME: SATISH
    SURNAME: BANDI
    AGE: 25
  tasks:
  - name: print details
    vars:
      NAME: THARUN
      SURNAME: KAKITLA
      AGE: 30
    ansible.builtin.debug:
      msg: "Hello My Name is {{ NAME }}, and Surname is {{ SURNAME }}, and My Age is {{ AGE }}"

  - name: print details again
    ansible.builtin.debug:
      msg: "Hello My Name is {{ NAME }}, and Surname is {{ SURNAME }}, and My Age is {{ AGE }}."