- name: varibale input from file
  hosts: local
  connection: local
  vars_files:
  - variablesinput.yaml
  tasks:
  - name: print details
    ansible.builtin.debug:
      msg: "Hello My Name is {{ NAME }}, and my surname is {{ SURNAME }}, and my age is {{ AGE }}."
