- name: install catalogue service
  hosts: catalogue
  become: yes
  tasks:
    - name: enable required version
      ansible.builtin.command: dnf module disable nodejs -y
      
    - name: enable required version
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: application user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: extract catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue servive
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: system daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: yes

    - name: start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes
    
    - name: copy mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongo client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check products loaded or not
      ansible.builtin.command: mongosh --host mongodb.satish84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: load data when ouput < 0
      ansible.builtin.shell: mongosh --host mongodb.satish84s.site </app/db/master-data.js
      when: catalogue_output.stdout | int < 0