- name: configure dispatch component
  hosts: dispatch
  become: yes
  tasks:
  - name: install golang
    ansible.builtin.dnf:
      name: golang
      state: installed
  
  - name: create system user
    ansible.builtin.user:
      user: roboshop
      home: /app
      shell: /sbin/nologin/
      system: yes

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: get url from git
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: go mod init dispatch
    args:
      chdir: /app

  - name: install dependencies
    ansible.builtin.command: go get
    args:
      chdir: /app

  - name: install dependencies
    ansible.builtin.command: go build
    args:
      chdir: /app

  - name: copy dispatch service file
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: start and enable the dispatch service
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes

  
