- name: install user module
  hosts: user
  become: yes
  tasks:
    - name: disable default nodejs version
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable required nodejs version
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: intstall nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: adding roboshop user
      ansible.builtin.user:
        name: roboshop
        system: yes
        shell: /sbin/nologin/
        home: /app

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: get code from git
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip
      
    - name: unzip code in app
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy user service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable user
      ansible.builtin.service:
        name: user
        state: started
        enabled: yes
    